// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUckTu_m2HR5k72q1aHsWqE5m1rvmdZfo',
    appId: '1:407432915878:web:3980bf0b3b0f5d3ca97d67',
    messagingSenderId: '407432915878',
    projectId: 'popcorn-a67e4',
    authDomain: 'popcorn-a67e4.firebaseapp.com',
    storageBucket: 'popcorn-a67e4.appspot.com',
    measurementId: 'G-23MRTN0WQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJwojkM6PLXLn4kFqc36YHoOrz_Dvg9s',
    appId: '1:407432915878:android:3269576be465584ca97d67',
    messagingSenderId: '407432915878',
    projectId: 'popcorn-a67e4',
    storageBucket: 'popcorn-a67e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfOXVNhXpJ4_HrjmoU4fMyWbNWDn6CME',
    appId: '1:407432915878:ios:c7e34b07cfc57a15a97d67',
    messagingSenderId: '407432915878',
    projectId: 'popcorn-a67e4',
    storageBucket: 'popcorn-a67e4.appspot.com',
    iosClientId:
        '407432915878-c8ucrgsku3239u2k72tieb7al9lbure6.apps.googleusercontent.com',
    iosBundleId: 'com.example.popcornV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAfOXVNhXpJ4_HrjmoU4fMyWbNWDn6CME',
    appId: '1:407432915878:ios:fe25ebb1cdff18d4a97d67',
    messagingSenderId: '407432915878',
    projectId: 'popcorn-a67e4',
    storageBucket: 'popcorn-a67e4.appspot.com',
    iosClientId:
        '407432915878-2ukeuqrbjmq1g252i5pkcvjph0vu25ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.popcornV2.RunnerTests',
  );
}
